import { ExpenseRecord, ExpenseSummaryKPIs } from "@/types/expenses";

export const mockExpensesKPIs: ExpenseSummaryKPIs = {
  totalExpensesAED: 120000,
  labourHandlingAED: 245000,
  freightLogisticsAED: 245000,
};

export const mockExpensesList: ExpenseRecord[] = [
  {
    id: "EXP-018",
    expenseCode: "EXP-018",
    businessId: "biz-1",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "10 Sep 2026",
    expenseDate: "2026-09-10",
    category: "Delivery / Transport",
    description: "Dubai to India shipment",
    paymentMethod: "Main Admin via Bank Wire",
    amount: 450.0,
    amountAED: 450.0,
    status: "CLEARED",
    selected: true,
    details: {
      settledAmount: 450.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Delivery / Transport",
      linkedContracts: {
        purchaseId: "PR-0248",
        purchaseCostAED: 112000,
        saleId: "SL-0248",
        saleRealizationAED: 142000,
      },
    },
  },
  {
    id: "EXP-019",
    expenseCode: "EXP-019",
    businessId: "biz-1",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "10 Sep 2026",
    expenseDate: "2026-09-10",
    category: "Labour",
    description: "Physical vault handling",
    paymentMethod: "Main Admin via Cash Voucher",
    amount: 350.0,
    amountAED: 350.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 350.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Cash Voucher",
      expenseClassification: "Labour & Vault",
      linkedContracts: {
        purchaseId: "PR-0248",
        purchaseCostAED: 112000,
        saleId: "SL-0248",
        saleRealizationAED: 142000,
      },
    },
  },
  {
    id: "EXP-020",
    expenseCode: "EXP-020",
    businessId: "biz-1",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "11 Sep 2026",
    expenseDate: "2026-09-11",
    category: "Other Expense",
    description: "Assaying & purity verification laboratory fee",
    paymentMethod: "Main Admin via Bank Wire",
    amount: 250.0,
    amountAED: 250.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 250.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Other Expense",
      linkedContracts: {
        purchaseId: "PR-0249",
        purchaseCostAED: 98000,
        saleId: "SL-0249",
        saleRealizationAED: 125000,
      },
    },
  },
  {
    id: "EXP-021",
    expenseCode: "EXP-021",
    businessId: "biz-2",
    business: "Business 02",
    businessEntity: "Entity A+C",
    entityLabel: "Business 02 (A + C)",
    date: "11 Sep 2026",
    expenseDate: "2026-09-11",
    category: "India Expense",
    description: "Domestic courier & door delivery logistics",
    paymentMethod: "Cash Handover Desk",
    amount: 800.0,
    amountAED: 800.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 800.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Cash Handover Desk",
      expenseClassification: "India Expense",
      linkedContracts: {
        purchaseId: "PR-0250",
        purchaseCostAED: 215000,
        saleId: "SL-0250",
        saleRealizationAED: 268000,
      },
    },
  },
  {
    id: "EXP-022",
    expenseCode: "EXP-022",
    businessId: "biz-2",
    business: "Business 02",
    businessEntity: "Entity A+C",
    entityLabel: "Business 02 (A + C)",
    date: "12 Sep 2026",
    expenseDate: "2026-09-12",
    category: "Transfer / Conversion",
    description: "Inter-bank telegraphic transfer fee & conversion spread",
    paymentMethod: "Bank Debit Auto-Charge",
    amount: 180.0,
    amountAED: 180.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 180.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Bank Debit Auto-Charge",
      expenseClassification: "Transfer / Conversion",
      linkedContracts: {
        purchaseId: "PR-0250",
        purchaseCostAED: 215000,
        saleId: "SL-0250",
        saleRealizationAED: 268000,
      },
    },
  },
  {
    id: "EXP-023",
    expenseCode: "EXP-023",
    businessId: "biz-2",
    business: "Business 02",
    businessEntity: "Entity A+C",
    entityLabel: "Business 02 (A + C)",
    date: "12 Sep 2026",
    expenseDate: "2026-09-12",
    category: "Labour",
    description: "Vaulting guard & security surcharge",
    paymentMethod: "Main Admin via Cash Voucher",
    amount: 320.0,
    amountAED: 320.0,
    status: "PENDING",
    selected: false,
    details: {
      settledAmount: 320.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Cash Voucher",
      expenseClassification: "Labour & Vault",
      linkedContracts: {
        purchaseId: "PR-0251",
        purchaseCostAED: 145000,
        saleId: "SL-0251",
        saleRealizationAED: 178000,
      },
    },
  },
];
