import { ExpenseRecord, ExpenseSummaryKPIs } from "@/types/expenses";

export const mockExpensesKPIs: ExpenseSummaryKPIs = {
  totalExpensesAED: 120000,
  labourHandlingAED: 245000,
  freightLogisticsAED: 245000,
};

export const mockExpensesList: ExpenseRecord[] = [
  {
    id: "EXP-018",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "10 Sep 2026",
    category: "Delivery / Transport",
    description: "Dubai to India shipment",
    ref: "DEL-8821",
    amountAED: 450.0,
    status: "CLEARED",
    selected: true,
    details: {
      settledAmount: 450.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Delivery / Transport",
      linkedContracts: {
        purchaseId: "PR-0248",
        purchaseCostAED: 112000,
        saleId: "SL-0248",
        saleRealizationAED: 142000,
      },
    },
  },
  {
    id: "EXP-019",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "10 Sep 2026",
    category: "Labour",
    description: "Physical vault handling",
    ref: "LAB-0921",
    amountAED: 350.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 350.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Cash Voucher",
      expenseClassification: "Labour & Vault",
      linkedContracts: {
        purchaseId: "PR-0248",
        purchaseCostAED: 112000,
        saleId: "SL-0248",
        saleRealizationAED: 142000,
      },
    },
  },
  {
    id: "EXP-020",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "10 Sep 2026",
    category: "Other Expense",
    description: "Processing & assaying",
    ref: "OPS-168",
    amountAED: 1200.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 1200.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Processing & Assaying",
      linkedContracts: {
        purchaseId: "PR-0248",
        purchaseCostAED: 112000,
        saleId: "SL-0248",
        saleRealizationAED: 142000,
      },
    },
  },
  {
    id: "EXP-021",
    business: "Business 02",
    businessEntity: "Entity A+C",
    entityLabel: "Business 02 (A + C)",
    date: "08 Sep 2026",
    category: "India Expense",
    description: "Local Zaveri Bazaar clearing",
    ref: "IND-772",
    amountAED: 4000.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 4000.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via RTGS Direct",
      expenseClassification: "India Realization Exp",
      linkedContracts: {
        purchaseId: "PR-0247",
        purchaseCostAED: 73400,
        saleId: "SL-0247",
        saleRealizationAED: 93600,
      },
    },
  },
  {
    id: "EXP-022",
    business: "Business 02",
    businessEntity: "Entity A+C",
    entityLabel: "Business 02 (A + C)",
    date: "08 Sep 2026",
    category: "Delivery / Transport",
    description: "BOM transit security escort",
    ref: "DEL-771",
    amountAED: 320.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 320.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Delivery / Transport",
      linkedContracts: {
        purchaseId: "PR-0247",
        purchaseCostAED: 73400,
        saleId: "SL-0247",
        saleRealizationAED: 93600,
      },
    },
  },
  {
    id: "EXP-023",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "07 Sep 2026",
    category: "Transfer / Conversion",
    description: "RTGS forex hedging handling",
    ref: "BNK-302",
    amountAED: 1650.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 1650.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Transfer / FX Fees",
      linkedContracts: {
        purchaseId: "PR-0246",
        purchaseCostAED: 195210,
        saleId: "Pending",
        saleRealizationAED: 0,
      },
    },
  },
];
