import { ExpenseRecord, ExpenseSummaryKPIs } from "@/types/expenses";

export const mockExpensesKPIs: ExpenseSummaryKPIs = {
  totalExpensesAED: 120000,
  labourHandlingAED: 245000,
  freightLogisticsAED: 245000,
};

export const mockExpensesList: ExpenseRecord[] = [
  {
    id: "EXP-018",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "10 Sep 2026",
    category: "Delivery / Transport",
    description: "Dubai to India shipment",
    cycle: "TR-0248",
    ref: "DEL-8821",
    amountAED: 450.0,
    status: "CLEARED",
    selected: true,
    details: {
      settledAmount: 450.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Delivery / Transport",
      cycleAllocation: "Trading Cycle TR-0248",
      cycleCategoryDistribution: {
        deliveryFreight: 1150.0,
        labourVault: 850.0,
        processingAssaying: 1200.0,
        indiaRealizationExp: 4000.0,
        transferFxFees: 1650.0,
      },
      cycleMarginalImpact: {
        cycleGrossSpread: 30000.0,
        thisRecord: -450.0,
        totalCycleExpenses: -6000.0,
        netCycleProfit: 24000.0,
        netCycleMargin: 16.9,
      },
      linkedContracts: {
        purchaseId: "PR-0248",
        purchaseCostAED: 112000,
        saleId: "SL-0248",
        saleRealizationAED: 142000,
        cycleId: "TR-0248",
        cycleStatus: "Completed",
      },
    },
  },
  {
    id: "EXP-019",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "10 Sep 2026",
    category: "Labour",
    description: "Physical vault handling",
    cycle: "TR-0248",
    ref: "LAB-0921",
    amountAED: 350.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 350.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Cash Voucher",
      expenseClassification: "Labour & Vault",
      cycleAllocation: "Trading Cycle TR-0248",
      cycleCategoryDistribution: {
        deliveryFreight: 1150.0,
        labourVault: 850.0,
        processingAssaying: 1200.0,
        indiaRealizationExp: 4000.0,
        transferFxFees: 1650.0,
      },
      cycleMarginalImpact: {
        cycleGrossSpread: 30000.0,
        thisRecord: -350.0,
        totalCycleExpenses: -6000.0,
        netCycleProfit: 24000.0,
        netCycleMargin: 16.9,
      },
      linkedContracts: {
        purchaseId: "PR-0248",
        purchaseCostAED: 112000,
        saleId: "SL-0248",
        saleRealizationAED: 142000,
        cycleId: "TR-0248",
        cycleStatus: "Completed",
      },
    },
  },
  {
    id: "EXP-020",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "10 Sep 2026",
    category: "Other Expense",
    description: "Processing & assaying",
    cycle: "TR-0248",
    ref: "OPS-168",
    amountAED: 1200.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 1200.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Processing & Assaying",
      cycleAllocation: "Trading Cycle TR-0248",
      cycleCategoryDistribution: {
        deliveryFreight: 1150.0,
        labourVault: 850.0,
        processingAssaying: 1200.0,
        indiaRealizationExp: 4000.0,
        transferFxFees: 1650.0,
      },
      cycleMarginalImpact: {
        cycleGrossSpread: 30000.0,
        thisRecord: -1200.0,
        totalCycleExpenses: -6000.0,
        netCycleProfit: 24000.0,
        netCycleMargin: 16.9,
      },
      linkedContracts: {
        purchaseId: "PR-0248",
        purchaseCostAED: 112000,
        saleId: "SL-0248",
        saleRealizationAED: 142000,
        cycleId: "TR-0248",
        cycleStatus: "Completed",
      },
    },
  },
  {
    id: "EXP-021",
    business: "Business 02",
    businessEntity: "Entity A+C",
    entityLabel: "Business 02 (A + C)",
    date: "08 Sep 2026",
    category: "India Expense",
    description: "Local Zaveri Bazaar clearing",
    cycle: "TR-0247",
    ref: "IND-772",
    amountAED: 4000.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 4000.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via RTGS Direct",
      expenseClassification: "India Realization Exp",
      cycleAllocation: "Trading Cycle TR-0247",
      cycleCategoryDistribution: {
        deliveryFreight: 920.0,
        labourVault: 650.0,
        processingAssaying: 1100.0,
        indiaRealizationExp: 4000.0,
        transferFxFees: 180.0,
      },
      cycleMarginalImpact: {
        cycleGrossSpread: 20200.0,
        thisRecord: -4000.0,
        totalCycleExpenses: -6850.0,
        netCycleProfit: 13350.0,
        netCycleMargin: 14.26,
      },
      linkedContracts: {
        purchaseId: "PR-0247",
        purchaseCostAED: 73400,
        saleId: "SL-0247",
        saleRealizationAED: 93600,
        cycleId: "TR-0247",
        cycleStatus: "Completed",
      },
    },
  },
  {
    id: "EXP-022",
    business: "Business 02",
    businessEntity: "Entity A+C",
    entityLabel: "Business 02 (A + C)",
    date: "08 Sep 2026",
    category: "Delivery / Transport",
    description: "BOM transit security escort",
    cycle: "TR-0247",
    ref: "DEL-771",
    amountAED: 320.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 320.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Delivery / Transport",
      cycleAllocation: "Trading Cycle TR-0247",
      cycleCategoryDistribution: {
        deliveryFreight: 920.0,
        labourVault: 650.0,
        processingAssaying: 1100.0,
        indiaRealizationExp: 4000.0,
        transferFxFees: 180.0,
      },
      cycleMarginalImpact: {
        cycleGrossSpread: 20200.0,
        thisRecord: -320.0,
        totalCycleExpenses: -6850.0,
        netCycleProfit: 13350.0,
        netCycleMargin: 14.26,
      },
      linkedContracts: {
        purchaseId: "PR-0247",
        purchaseCostAED: 73400,
        saleId: "SL-0247",
        saleRealizationAED: 93600,
        cycleId: "TR-0247",
        cycleStatus: "Completed",
      },
    },
  },
  {
    id: "EXP-023",
    business: "Business 01",
    businessEntity: "Entity A+B",
    entityLabel: "Business 01 (A + B)",
    date: "07 Sep 2026",
    category: "Transfer / Conversion",
    description: "RTGS forex hedging handling",
    cycle: "TR-0246",
    ref: "BNK-302",
    amountAED: 1650.0,
    status: "CLEARED",
    selected: false,
    details: {
      settledAmount: 1650.0,
      settlementCurrency: "AED (United Arab Emirates Dirham)",
      disbursedBy: "Main Admin via Bank Wire",
      expenseClassification: "Transfer / FX Fees",
      cycleAllocation: "Trading Cycle TR-0246",
      cycleCategoryDistribution: {
        deliveryFreight: 0,
        labourVault: 0,
        processingAssaying: 0,
        indiaRealizationExp: 0,
        transferFxFees: 1650.0,
      },
      cycleMarginalImpact: {
        cycleGrossSpread: 0,
        thisRecord: -1650.0,
        totalCycleExpenses: -1650.0,
        netCycleProfit: 0,
        netCycleMargin: 0,
      },
      linkedContracts: {
        purchaseId: "PR-0246",
        purchaseCostAED: 195210,
        saleId: "Pending",
        saleRealizationAED: 0,
        cycleId: "TR-0246",
        cycleStatus: "In Progress",
      },
    },
  },
];
