import { InvestorRecord, InvestorSummaryKPIs } from "@/types/investors";

export const mockInvestorsKPIs: InvestorSummaryKPIs = {
  totalInvestors: 3,
  totalInvestmentAED: 245000,
  profitPaid: 1,
  netRealizedProfitAED: 35990,
};

export const mockInvestorsList: InvestorRecord[] = [
  {
    id: "INV-003",
    name: "Partner C",
    emailOrSubtitle: "INV-003 • partnerc@ivora-trade.ae",
    business: "Business 02",
    businessEntity: "Entity A + C",
    entityLabel: "Business 02 (A + C) • INV-003",
    investmentAED: 100000,
    date: "18 Aug 2026",
    sharePercent: 35,
    allocatedProfitAED: 5340,
    paidAED: 2690,
    outstandingAED: 2650,
    status: "ACTIVE",
    selected: false,
    details: {
      totalInvestmentAED: 100000,
      profitShare: "35%",
      profitShareContract: "Contracted Ratio",
      allocatedProfit: 5340,
      outstandingBalance: 2650,
      paidAmount: 2690,
      cycleAllocation: {
        cycleId: "TR-0247",
        netCycleProfitAED: 15257,
        contractedRatio: "× 35%",
        investorProfitCreditAED: 5340,
        allocationDate: "18 Aug 2026",
        status: "Partially Settled",
      },
      recentTransactions: [
        {
          id: "SET-007",
          title: "Settlement SET-007",
          date: "20 Aug 2026",
          reference: "ENBD Ref #98124",
          amountFormatted: "Paid AED 2,690",
          type: "BANK TRANSFER",
        },
        {
          id: "TR-0247",
          title: "Profit Allocation TR-0247",
          date: "18 Aug 2026",
          reference: "Trading Cycle Close",
          amountFormatted: "AED 5,340 Calculated",
          type: "AUTOMATED",
        },
        {
          id: "CAP-003",
          title: "Initial Investment Capital",
          date: "10 Aug 2026",
          reference: "Escrow Business 02",
          amountFormatted: "AED 100,000 Cleared",
          type: "INWARD REMITTANCE",
        },
      ],
    },
  },
  {
    id: "INV-002",
    name: "Partner B",
    isMultiEntity: true,
    emailOrSubtitle: "INV-002 — Multi-Entity Participation",
    business: "Business 03",
    businessEntity: "Entity A + B2",
    entityLabel: "Business 01 (A + B) • INV-002",
    investmentAED: 75000,
    date: "01 Sep 2026",
    sharePercent: 25,
    allocatedProfitAED: 0,
    paidAED: 0,
    outstandingAED: 0,
    status: "PENDING",
    selected: true,
    details: {
      totalInvestmentAED: 150000,
      profitShare: "40%",
      profitShareContract: "Manual Contract",
      allocatedProfit: 9600,
      outstandingBalance: 3600,
      paidAmount: 6000,
      cycleAllocation: {
        cycleId: "TR-0248",
        netCycleProfitAED: 24000,
        contractedRatio: "× 40%",
        investorProfitCreditAED: 9600,
        allocationDate: "10 Sep 2026",
        status: "Partially Settled",
      },
      recentTransactions: [
        {
          id: "SET-008",
          title: "Settlement SET-008",
          date: "10 Sep 2026",
          reference: "ENBD Ref #99281",
          amountFormatted: "Paid AED 6,000",
          type: "BANK TRANSFER",
        },
        {
          id: "TR-0248",
          title: "Profit Allocation TR-0248",
          date: "10 Sep 2026",
          reference: "Trading Cycle Close",
          amountFormatted: "AED 9,600 Calculated",
          type: "AUTOMATED",
        },
        {
          id: "CAP-002",
          title: "Initial Investment Capital",
          date: "12 Aug 2026",
          reference: "Escrow Business 01",
          amountFormatted: "AED 150,000 Cleared",
          type: "INWARD REMITTANCE",
        },
      ],
    },
  },
  {
    id: "INV-001",
    name: "Global Syndicate Alpha",
    emailOrSubtitle: "INV-001 • institutional@alpha.sg",
    business: "Business 01",
    businessEntity: "Entity A + B",
    entityLabel: "Business 01 (A + B) • INV-001",
    investmentAED: 500000,
    date: "04 Jul 2026",
    sharePercent: 50,
    allocatedProfitAED: 38400,
    paidAED: 38400,
    outstandingAED: 0,
    status: "CLEARED",
    selected: false,
    details: {
      totalInvestmentAED: 500000,
      profitShare: "50%",
      profitShareContract: "Standard Institutional",
      allocatedProfit: 38400,
      outstandingBalance: 0,
      paidAmount: 38400,
      cycleAllocation: {
        cycleId: "TR-0245",
        netCycleProfitAED: 76800,
        contractedRatio: "× 50%",
        investorProfitCreditAED: 38400,
        allocationDate: "04 Jul 2026",
        status: "Fully Settled",
      },
      recentTransactions: [
        {
          id: "SET-001",
          title: "Settlement SET-001",
          date: "08 Jul 2026",
          reference: "DBS Institutional Wire",
          amountFormatted: "Paid AED 38,400",
          type: "BANK TRANSFER",
        },
        {
          id: "TR-0245",
          title: "Profit Allocation TR-0245",
          date: "04 Jul 2026",
          reference: "Trading Cycle Close",
          amountFormatted: "AED 38,400 Calculated",
          type: "AUTOMATED",
        },
        {
          id: "CAP-001",
          title: "Initial Investment Capital",
          date: "01 Jul 2026",
          reference: "Escrow Institutional",
          amountFormatted: "AED 500,000 Cleared",
          type: "INWARD REMITTANCE",
        },
      ],
    },
  },
];
