import { TradingCycleRecord, TradingCycleSummaryKPIs } from "@/types/trading-cycle";

export const mockTradingCycleKPIs: TradingCycleSummaryKPIs = {
  totalCycles: 3,
  completedCycles: 2,
  pendingCycles: 1,
  netRealizedProfitAED: 35990,
};

export const mockTradingCycleList: TradingCycleRecord[] = [
  {
    id: "TR-0248",
    business: "Business 01",
    businessEntity: "Business 01 (Entity A + B)",
    partnerSplit: "A+B (60/40)",
    equityRatio: "60% / 40%",
    purchaseId: "PR-0248",
    purchaseLocation: "Dubai Gold Souk • 6,500 GMS",
    purchaseCost: 112000,
    saleId: "SL-0248",
    saleLocation: "Zaveri Bazaar India Vault",
    realizationAED: 142000,
    realizationINRLakhs: "₹ 32.28L",
    quantityGms: 6500,
    commodity: "999.9 Bullion",
    productType: "Gold Bullion",
    grossProfit: 30000,
    expenses: 6000,
    netProfit: 24000,
    marginPercent: 16.90,
    status: "COMPLETED",
    selected: true,
    matchId: "MATCH ID #9042",
    inrNominalRealized: "₹ 32,28,000.00",
    executionCrossRate: "₹ 22.7400 / AED",
    fxSlippageVariance: "0.00 BPS (Fixed Contract)",
    fxSettlementStatus: "CLEARED & DISBURSED",
    partnerBShare: {
      name: "Partner B (External Investor)",
      subtext: "Contracted 40% Arbitrage Share",
      amount: 9600.00,
      settledInfo: "Settled: AED 6k | Bal: AED 3.6k",
    },
    deskRetainedShare: {
      name: "Desk Retained Profit",
      subtext: "IVORA Entity A 60% Retained",
      amount: 14400.00,
      settledInfo: "100% Cleared to Escrow",
    },
  },
  {
    id: "TR-0247",
    business: "Business 02",
    businessEntity: "Business 02 (Entity A + C)",
    partnerSplit: "A+C (65/35)",
    equityRatio: "65% / 35%",
    purchaseId: "PR-0247",
    purchaseLocation: "Dubai Gold Souk • 5,200 GMS",
    purchaseCost: 73400,
    saleId: "SL-0247",
    saleLocation: "Mumbai Vault",
    realizationAED: 93600,
    realizationINRLakhs: "₹ 21.36L",
    quantityGms: 5200,
    commodity: "Gold Grain 995",
    productType: "Gold Grain 995",
    grossProfit: 20200,
    expenses: 6850,
    netProfit: 13350,
    marginPercent: 14.26,
    status: "COMPLETED",
    selected: false,
    matchId: "MATCH ID #9041",
    inrNominalRealized: "₹ 21,29,544.00",
    executionCrossRate: "₹ 22.7500 / AED",
    fxSlippageVariance: "0.00 BPS (Fixed Contract)",
    fxSettlementStatus: "CLEARED & DISBURSED",
    partnerBShare: {
      name: "Partner C (External Investor)",
      subtext: "Contracted 35% Arbitrage Share",
      amount: 4672.50,
      settledInfo: "Settled: AED 4.67k | Bal: AED 0",
    },
    deskRetainedShare: {
      name: "Desk Retained Profit",
      subtext: "IVORA Entity A 65% Retained",
      amount: 8677.50,
      settledInfo: "100% Cleared to Escrow",
    },
  },
  {
    id: "TR-0246",
    business: "Business 01",
    businessEntity: "Business 01 (Entity A + B)",
    partnerSplit: "A+B (60/40)",
    equityRatio: "60% / 40%",
    purchaseId: "PR-0246",
    purchaseLocation: "Dubai Gold Souk • 6,840 GMS",
    purchaseCost: 195210,
    saleId: "Pending (Zaveri Escort)",
    saleLocation: "Pending (Transit Escort)",
    realizationAED: null,
    realizationINRLakhs: null,
    quantityGms: 6840,
    commodity: "Pure Bullion",
    productType: "Pure Bullion",
    grossProfit: null,
    expenses: null,
    netProfit: null,
    marginPercent: null,
    status: "IN PROGRESS",
    selected: false,
    matchId: "MATCH ID #9040",
    inrNominalRealized: "Pending Sale",
    executionCrossRate: "Pending FX",
    fxSlippageVariance: "—",
    fxSettlementStatus: "IN TRANSIT",
    partnerBShare: {
      name: "Partner B (External Investor)",
      subtext: "Contracted 40% Arbitrage Share",
      amount: 0,
      settledInfo: "Pending Cycle Settlement",
    },
    deskRetainedShare: {
      name: "Desk Retained Profit",
      subtext: "IVORA Entity A 60% Retained",
      amount: 0,
      settledInfo: "Pending Cycle Settlement",
    },
  },
];
