import { BusinessEntity, BusinessesSummaryKPIs } from "@/types/business";

export const mockBusinessesKPIs: BusinessesSummaryKPIs = {
  totalBusinesses: 3,
  activeBusinesses: 2,
  totalPartners: 3,
  combinedInvestmentAED: 235600,
  combinedNetProfitAED: 37350,
};

export const mockBusinessesList: BusinessEntity[] = [
  {
    id: "b1",
    name: "Business 01",
    code: "B01-DXB-BOM",
    subtitle: "Dubai Bullion & Direct Zaveri Liquidation • B01-DXB-BOM",
    partners: [
      { name: "Admin A", sharePercentage: 60 },
      { name: "Partner B", sharePercentage: 40 },
    ],
    partnersSummary: "Admin A (60%) + Partner B (40%)",
    investmentAED: 150000,
    purchaseCostAED: 112000,
    salesIndiaAED: 142000,
    expensesAED: 8000,
    netProfitAED: 24000,
    marginPercentage: 16.9,
    status: "ACTIVE",
    createdAt: "12 Aug 2026",
    productType: "Gold Bullion",
    locationRoute: "Dubai (DXB) → Mumbai (BOM)",
  },
  {
    id: "b2",
    name: "Business 02",
    code: "B02-DXB-DEL",
    subtitle: "Secondary Precious Metals & Granulated Silver • B02-DXB-DEL",
    partners: [
      { name: "Admin A", sharePercentage: 65 },
      { name: "Partner C", sharePercentage: 35 },
    ],
    partnersSummary: "Admin A (65%) + Partner C (35%)",
    investmentAED: 100000,
    purchaseCostAED: 73400,
    salesIndiaAED: 93600,
    expensesAED: 4850,
    netProfitAED: 13350,
    marginPercentage: 14.26,
    status: "ACTIVE",
    createdAt: "18 Aug 2026",
    productType: "Granulated Silver",
    locationRoute: "Dubai (DXB) → Delhi (DEL)",
  },
  {
    id: "b3",
    name: "Business 02",
    code: "B02-DXB-DEL",
    subtitle: "Secondary Precious Metals & Granulated Silver • B02-DXB-DEL",
    partners: [
      { name: "Admin A", sharePercentage: 65 },
      { name: "Partner C", sharePercentage: 35 },
    ],
    partnersSummary: "Admin A (65%) + Partner C (35%)",
    investmentAED: 100000,
    purchaseCostAED: 73400,
    salesIndiaAED: 93600,
    expensesAED: 4850,
    netProfitAED: 13350,
    marginPercentage: 14.26,
    status: "ACTIVE",
    createdAt: "18 Aug 2026",
    productType: "Granulated Silver",
    locationRoute: "Dubai (DXB) → Delhi (DEL)",
  },
  {
    id: "b4",
    name: "Business 02",
    code: "B02-DXB-DEL",
    subtitle: "Secondary Precious Metals & Granulated Silver • B02-DXB-DEL",
    partners: [
      { name: "Admin A", sharePercentage: 65 },
      { name: "Partner C", sharePercentage: 35 },
    ],
    partnersSummary: "Admin A (65%) + Partner C (35%)",
    investmentAED: 100000,
    purchaseCostAED: 73400,
    salesIndiaAED: 93600,
    expensesAED: 4850,
    netProfitAED: 13350,
    marginPercentage: 14.26,
    status: "ACTIVE",
    createdAt: "18 Aug 2026",
    productType: "Granulated Silver",
    locationRoute: "Dubai (DXB) → Delhi (DEL)",
  },
];
