import { PurchaseRecord, PurchaseSummaryKPIs } from "@/types/purchase";

export const mockPurchaseKPIs: PurchaseSummaryKPIs = {
  totalPurchase: 3,
  totalSourcingCostAED: 186000,
  logisticsOverheadAED: 1200,
};

export const mockPurchasesList: PurchaseRecord[] = [
  {
    id: "PR-0248",
    business: "Business 01",
    businessEntities: "Entity A + B",
    date: "10 Sep 2026",
    product: "999.9 Physical Bullion",
    locationVault: "Souk Node #04 Vault",
    quantity: 6500,
    quantityUnit: "GRAM",
    quantityGms: 6500,
    baseAmount: 31.2,
    basePriceAED: 31.2,
    basePricePerUnitAED: 31.2,
    totalPurchaseAmount: 202800,
    baseAcquisitionValue: 202800,
    freightAED: 450,
    labourAED: 350,
    totalLandedAED: 204800,
    status: "CLEARED",
    selected: true,
  },
  {
    id: "PR-0247",
    business: "Business 02",
    businessEntities: "Entity A + C",
    date: "08 Sep 2026",
    product: "Gold Grain 995",
    locationVault: "Refinery Consignment A",
    quantity: 5200,
    quantityUnit: "GRAM",
    quantityGms: 5200,
    baseAmount: 29.8,
    basePriceAED: 29.8,
    basePricePerUnitAED: 29.8,
    totalPurchaseAmount: 154960,
    baseAcquisitionValue: 154960,
    freightAED: 320,
    labourAED: 280,
    totalLandedAED: 156290,
    status: "IN PROGRESS",
    selected: false,
  },
  {
    id: "PR-0246",
    business: "Business 01",
    businessEntities: "Entity A + B",
    date: "06 Sep 2026",
    product: "Pure Bullion Bar",
    locationVault: "DIFC Clearing Hub",
    quantity: 6840,
    quantityUnit: "GRAM",
    quantityGms: 6840,
    baseAmount: 28.4,
    basePriceAED: 28.4,
    basePricePerUnitAED: 28.4,
    totalPurchaseAmount: 194256,
    baseAcquisitionValue: 194256,
    freightAED: 290,
    labourAED: 240,
    totalLandedAED: 195210,
    status: "DRAFT",
    selected: false,
  },
];
